### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Albert221** [Albert221/FastShopping#43]
![image](https://user-images.githubusercontent.com/4085280/102021277-0fca7700-3d7f-11eb-9eff-0c3534e2ea28.png)

- [x] Settings screen #58

Settings in the app with the ability to change some application behaviors and appearance:

- [x] Shopping lists mode #15
- [x] Items density #40 (comfortable and compact?)
- [ ] ~Default items sorting, (partially) #18 (by creation date ascending, descending, by title)~
- [x] Always move done items to the bottom (defaults to false) #62
- [x] Dark mode #7 #61

Also, move _Support the author_ and _Licenses_ to the bottom of _Settings_.

**Comment by 766F6964** [comment]
Would be nice to be able to change the accent colors of the app, and potentially having a dark mode.

**Comment by Albert221** [comment]
![image](https://user-images.githubusercontent.com/4085280/105777060-003b7200-5f6a-11eb-9b84-8901fa2856cd.png)
